// Select the shuttle element
const shuttle = document.querySelector('.shuttle');

// Generated by Copilot
let scrollPosition = 0;

// Event listener to track scroll
window.addEventListener('scroll', () => {
    scrollPosition = window.pageYOffset || document.documentElement.scrollTop;
    requestAnimationFrame(animateShuttle);
});

function animateShuttle() {
    // Calculate the window height and document height
    const windowHeight = window.innerHeight;
    const documentHeight = document.documentElement.scrollHeight;
    const maxScroll = documentHeight - windowHeight;
    const scrollPercentage = scrollPosition / maxScroll;
    shuttle.style.transform = `translateY(${(1 - scrollPercentage) * 100}vh)`;
}