// Generated by Copilot
window.addEventListener('scroll', function() {
    const shuttle = document.getElementById('shuttle');
    const scrollPosition = window.scrollY;
    
    // Calculate the new position of the shuttle based on scroll
    const newPosition = Math.min(80, 20 + scrollPosition / 10); // Adjust the divisor for speed
    shuttle.style.top = newPosition + '%';
});
// JavaScript code for handling scroll events can be added here